### PR TITLE
Add the missing console input stream delegate

### PR DESCRIPTION
**Pull request by opeongo**
The console delegate methods in Interpreter were missing a method to change the input stream.  This PR adds the missing method.

### CODE REVIEW

**Comment by opeongo** [comment]
This PR seems to have been mangled by the forced-push that was done last month.  Does it need to deleted and pushed again?

**Comment by nickl-** [comment]
> This PR seems to have been mangled by the forced-push that was done last month. Does it need to deleted and pushed again?

Something is funny with the code coverage too, would you mind terribly to redo the PR please?

**Comment by nickl-** [comment]
Not sure why the build failed for Java 11. Looks straight forward enough.

Lets see what happens when we merge.

**Comment by nickl-** [comment]
Build succeeded \o/

**Pull request merged**
