### PR TITLE
added history methods

### PR DESCRIPTION
**Pull request by amitabh123**
Added methods to add and get console history

### CODE REVIEW

**Comment by nickl-** [comment]
Is this all of it? Seems like there are some things missing from this PR.

**Comment by nickl-** [comment]
This PR is incomplete, the two accessor stubs is all that was submitted, there is no  actual history  implementation.

Closing the issue as incomplete, should you still want to complete see this added, please resubmit something more complete and we will gladly work with you to get it committed.

**Comment by nickl-** [comment]
Closed as incomplete.

**Comment by amitabh123** [comment]
Hi nickl, 

I use this as follows (Scala code)

```
    def addHistory(seq:Seq[String]) = seq foreach console.addHistory
    
    val history = readTextFileToString(historyFile).split('\n')
    addHistory(history)

```
So the idea is that history files will be managed by the application. The two methods provide the developer to manage the history of beanshell.

Hope this helps and the commit is accepted.

**Comment by nickl-** [comment]
@amitabh123 thank you for the explanation

If I understand you correctly this is command (typed in) history for the jConsole swing shell?

I agree having history makes the world of difference!

I use personally use [hanslub42/rlwrap](/hanslub42/rlwrap) to wrap the terminal interactive interpreter which improves the deadline support but more importantly saves the history as well.

the command I use is:

```
rlwrap -aiI -Cbsh -pBlue java -classpath bsh-2.1.0-SNAPSHOT.jar bsh.Interpreter
```

One of our community members @stefanofornari has started a project which shows promise and implements jline support it already boasts working persisted command history [stefanofornari/BshConsole](/stefanofornari/BshConsole)

It would probably make more sense to put our efforts into BshConsole instead of reinventing the wheel but I will open this issue again as a reminder.

**Comment by nickl-** [comment]
Closed: in favour of [stefanofornari/BshConsole](/stefanofornari/BshConsole)

**Pull request closed without merging**
