### PR TITLE
Unimplemented boolean operators - Implemented.

### PR DESCRIPTION
**Pull request by nickl-**
The boolean operators for bitwise and, bitwise or and XOR is now implemented.
Added index to the token image for convenience.

### CODE REVIEW

**Comment by nickl-** [comment]
Forgot to add... all built against JDK 1.8 - Did I hear anyone say Lambda Expressions? =)

**Comment by nickl-** [comment]
This goes towards the GoogleReports Tests...

**Comment by stain** [comment]
Thanks! I've merged and invited you to the beanshell github org! :)

**Comment by nickl-** [comment]
Awesome! I was just glad to see some attention but this is progress :D

**Pull request closed without merging**
