### PR TITLE
Fix for Issue #234, allow delete at start of line.

### PR DESCRIPTION
**Pull request by opeongo**
Please consider accepting this patch that addresses the second part of issue #234

### CODE REVIEW

**Comment by nickl-** [comment]
See comment #234

**Comment by leginee** [comment]
In order to get accepted, this PR needs to add unit test for the test coverage?

**Comment by opeongo** [comment]
This fix is for a visual aspect of  an interactive component.  I am not sure how you would set up a test.  Certainly there is no capability for this in the existing test harness.

**Comment by nickl-** [comment]
This one slipped through the cracks and then life happened.

**Pull request merged**
