### PR TITLE
Fix issue #753

### PR DESCRIPTION
**Pull request by opeongo**
- formal comments were always screened out, now are handled
- add test

### CODE REVIEW

**Comment by nickl-** [comment]
Looks good

**Comment by opeongo** [comment]
Need #732 merged before I can fix [bshdoc.bsh](https://github.com/beanshell/beanshell/blob/b35aac408f9c86ec20f1201a5ae9582ed99e2ae2/scripts/bshdoc.bsh).  It also has a problem with method lookups, where the interpreter has trouble distinguishing ```bshdoc(String)``` from ```bshdoc(String[])```.

**Comment by nickl-** [comment]
> Need #732 merged before I can fix [bshdoc.bsh](https://github.com/beanshell/beanshell/blob/b35aac408f9c86ec20f1201a5ae9582ed99e2ae2/scripts/bshdoc.bsh). It also has a problem with method lookups, where the interpreter has trouble distinguishing `bshdoc(String)` from `bshdoc(String[])`.

Not sure how this relates to this issue, this PR is closed right?

**Comment by opeongo** [comment]
The first version was a minimal fix that only worked with formal comments that had two **.   Other formal comment styles (three of more * or formal comments within statements) would be still be ignored or would cause parsing errors.

I have another version that fixes all the problems with parsing Java comments.  In this new patch BeanShell properly parse comments the same way as Java.  The consequence is dropping the BSHFormalComment node and adding a few accessor methods to obtain comments.

I updated bshdoc.bsh to use the new accessors, even though it is not being used in the build at the moment.  At least this should the new methodology for working with comments in the parser.

**Comment by nickl-** [comment]
#756 has been reviewed

**Pull request merged**
