### PR TITLE
Update checkstyle to latest version

### PR DESCRIPTION
**Pull request by stefanofornari**
In relation to issue #492 , I suspected a bug in checkstyle and it seems it was the case. Updating checkstyle to the latest version, fixed the problem. I am submitting this PR in the case you want to update it in trunk. Maybe others like me may incur in the same (still without root cause) issue.

### CODE REVIEW

**Comment by opeongo** [comment]
I have run checkstyle locally without any errors, but when I submit a PR the travis agent runs checkstyle and has caught trailing spaces that I missed.  What do I need to do to get the same style guide as is used for this project on github?  Is this issue related to my problem?

**Comment by nickl-** [comment]
@opeongo the style guide is supposed to be at [src/conf/checkstyle-supressions.xml](https://github.com/beanshell/beanshell/blob/merge-fork-beanshell2/src/conf/checkstyle-supressions.xml)

Needs testing and reduction of unnecessary commits.

**Comment by stefanofornari** [comment]
Replaced by #509

**Comment by nickl-** [comment]
@stefanofornari  #509 is not related

**Comment by nickl-** [comment]
The correct reference is #519

**Pull request closed without merging**
